package oanh;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import otest.JavaConnect;
import otest.Login;
import java.awt.HeadlessException;
Textimport java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Tài
 */
public class frmDoiMatKhau extends javax.swing.JInternalFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    String userName = Login.useNameLogin;
    String passWord = Login.passWordLogin;

    /**
     * Creates new form ThongKe
     */
    public frmDoiMatKhau() {
        initComponents();
        conn = JavaConnect.ConnectDB();
        //set name to text field tai khoan
        lbTaiKhoan.setText(userName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTaiKhoan = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pFMatKhauCu = new javax.swing.JPasswordField();
        pFMatKhauNhapLai = new javax.swing.JPasswordField();
        lbTaiKhoan = new javax.swing.JLabel();
        btnTaiKhoanLuu = new javax.swing.JButton();
        btnTaiKHoanHuy = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setTitle("Tài khoản");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đổi mật khẩu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(3000, 3000));
        jPanel1.setName(""); // NOI18N

        jLabel2.setText("Mật khẩu  :");

        jLabel4.setText("Nhập lại mật khẩu :");

        lbTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTaiKhoan.setForeground(new java.awt.Color(0, 0, 153));

        btnTaiKhoanLuu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTaiKhoanLuu.setForeground(new java.awt.Color(0, 0, 204));
        btnTaiKhoanLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/45.png"))); // NOI18N
        btnTaiKhoanLuu.setText("Lưu");
        btnTaiKhoanLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanLuuActionPerformed(evt);
            }
        });

        btnTaiKHoanHuy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTaiKHoanHuy.setForeground(new java.awt.Color(153, 0, 0));
        btnTaiKHoanHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Remove.png"))); // NOI18N
        btnTaiKHoanHuy.setText("Hủy");
        btnTaiKHoanHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKHoanHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                        .addComponent(lbTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pFMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(41, 41, 41)
                                .addComponent(pFMatKhauNhapLai, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(btnTaiKhoanLuu)
                .addGap(46, 46, 46)
                .addComponent(btnTaiKHoanHuy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pFMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pFMatKhauNhapLai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaiKhoanLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaiKHoanHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/userChangePassword.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user-groups.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaiKhoanLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanLuuActionPerformed
        String tk = lbTaiKhoan.getText();
        String matKhauCu = pFMatKhauCu.getText();
        String matKhauMoi = pFMatKhauMoi.get();
        String matKhauMoiAgain = pFMatKhauNhapLai.getText();
        if (tk.equals(userName) && matKhauCu.equals(passWord)) {
            if ((matKhauMoi != null) && (matKhauMoiAgain != null)) {
                if (!matKhauCu.equals(matKhauMoi)) {
                    if (matKhauMoi.equals(matKhauMoiAgain)) {
                        try {
                            String sql = "update login set usename='" + tk + "',password='" + matKhauMoi + "' where usename='" + tk + "' ";
                            pst = conn.prepareStatement(sql);
                            pst.execute();
                            JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công");
                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Nhập lại mật khẩu mới không đúng");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Mật khẩu mới trùng mật khẩu cũ");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Mật khẩu mới bị trống");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Mật khẩu cũ không đúng");
        }

    }//GEN-LAST:event_btnTaiKhoanLuuActionPerformed

    private void btnTaiKHoanHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKHoanHuyActionPerformed
        pFMatKhauCu.setText("");
        pFMatKhauMoi.setText("");
        pFMatKhauNhapLai.setText("");
    }//GEN-LAST:event_btnTaiKHoanHuyActionPerformed

    private void themTaiKhoan(String use, String pass, boolean admin) {
        String sql = "Insert into login(usename,password,admin) values (?,?,?)";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, use);
            pst.setString(2, pass);
            pst.setBoolean(3, admin);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Thêm tài khoản thành công");
            pst.close();
            rs.close();
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaiKHoanHuy;
    private javax.swing.JButton btnTaiKhoanLuu;
    private javax.swing.ButtonGroup buttonGroupTaiKhoan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbTaiKhoan;
    private javax.swing.JPasswordField pFMatKhauCu;
    private javax.swing.JPasswordField pFMatKhauNhapLai;
    // End of variables declaration//GEN-END:variables
}
