/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oanh;

/**
 *
 * @author oanh
 * 14/5/2023
 * Cai Dat Lop frmSanPham
 */
public class frmSanPham extends javax.swing.JFrame {

    /**
     * Creates new form frmSanPham
     */
    public frmSanPham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelTitle = new javax.swing.JPanel();
        TitleSanPham = new javax.swing.JLabel();
        panelSearch = new javax.swing.JPanel();
        inputSearch = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        panelCardSP = new javax.swing.JPanel();
        CardSanPham = new javax.swing.JPanel();
        lblTensanpham = new javax.swing.JLabel();
        lblGiasanpham = new javax.swing.JLabel();
        btnMuahang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelTitle.setLayout(new javax.swing.BoxLayout(panelTitle, javax.swing.BoxLayout.LINE_AXIS));

        TitleSanPham.setText("MÀN HÌNH SẢN PHẨM");
        panelTitle.add(TitleSanPham);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 394;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 200, 0);
        getContentPane().add(panelTitle, gridBagConstraints);

        panelSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelSearch.setLayout(new java.awt.GridLayout());
        panelSearch.add(inputSearch);

        btnTimKiem.setText("Tìm Kiếm");
        panelSearch.add(btnTimKiem);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(panelSearch, gridBagConstraints);

        panelCardSP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CardSanPham.setLayout(new java.awt.GridLayout(3, 0));

        lblTensanpham.setText("Tên sản phẩm:");
        CardSanPham.add(lblTensanpham);

        lblGiasanpham.setText("Gía sản phẩm ");
        CardSanPham.add(lblGiasanpham);

        btnMuahang.setText("Mua Hàng");
        CardSanPham.add(btnMuahang);

        javax.swing.GroupLayout panelCardSPLayout = new javax.swing.GroupLayout(panelCardSP);
        panelCardSP.setLayout(panelCardSPLayout);
        panelCardSPLayout.setHorizontalGroup(
            panelCardSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCardSPLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(CardSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
        );
        panelCardSPLayout.setVerticalGroup(
            panelCardSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCardSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CardSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(panelCardSP, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardSanPham;
    private javax.swing.JLabel TitleSanPham;
    private javax.swing.JButton btnMuahang;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JLabel lblGiasanpham;
    private javax.swing.JLabel lblTensanpham;
    private javax.swing.JPanel panelCardSP;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JPanel panelTitle;
    // End of variables declaration//GEN-END:variables
}
