/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sokkimthanh.menuchitietsanpham;

/**
 *
 * @author Thanh
 */
public class JPanelSPChiTiet extends javax.swing.JPanel {

    /**
     * Creates new form JPanelSPChiTiet
     */
    public JPanelSPChiTiet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabSPChiTiet = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblThongTinHanSuDung = new javax.swing.JLabel();
        lblGiaBanMoi = new javax.swing.JLabel();
        lblGiaBanCu = new javax.swing.JLabel();
        lblGiamGia = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblTenSP = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 233, 233));
        setForeground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1071, 899));
        setLayout(new java.awt.GridLayout(1, 0));

        TabSPChiTiet.setBackground(java.awt.Color.white);
        TabSPChiTiet.setForeground(java.awt.Color.black);
        TabSPChiTiet.setToolTipText("");
        TabSPChiTiet.setRequestFocusEnabled(false);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true)));
        jPanel1.setForeground(java.awt.Color.black);
        jPanel1.setPreferredSize(new java.awt.Dimension(1071, 899));

        lblThongTinHanSuDung.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblThongTinHanSuDung.setForeground(java.awt.Color.black);
        lblThongTinHanSuDung.setText("HSD trên 10 tháng");

        lblGiaBanMoi.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblGiaBanMoi.setForeground(java.awt.Color.black);
        lblGiaBanMoi.setText("28.800₫");

        lblGiaBanCu.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblGiaBanCu.setForeground(java.awt.Color.gray);
        lblGiaBanCu.setText("28.800₫");
        lblGiaBanCu.setToolTipText("");

        lblGiamGia.setBackground(java.awt.Color.red);
        lblGiamGia.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblGiamGia.setForeground(java.awt.Color.red);
        lblGiamGia.setText("-12%");

        jButton1.setBackground(new java.awt.Color(64, 158, 254));
        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Chọn mua");

        lblTenSP.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lblTenSP.setEditable(false);
        lblTenSP.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        lblTenSP.setName("Tên sản phẩm"); // NOI18N
        lblTenSP.setText("Sữa đặc có đường Dutch Lady lon 380g"); // NOI18N
        lblTenSP.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                lblTenSPTextValueChanged(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sokkimthanh/menuchitietsanpham/imgSP.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(lblThongTinHanSuDung))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(lblGiaBanMoi)
                        .addGap(111, 111, 111)
                        .addComponent(lblGiaBanCu)
                        .addGap(117, 117, 117)
                        .addComponent(lblGiamGia))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jButton1)
                        .addGap(57, 57, 57)
                        .addComponent(lblThongTinHanSuDung)
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGiaBanMoi)
                            .addComponent(lblGiaBanCu)
                            .addComponent(lblGiamGia)))))
        );

        TabSPChiTiet.addTab("Chi tiết sản phẩm", jPanel1);

        add(TabSPChiTiet);

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("Sản phẩm chi tiết");
        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void lblTenSPTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_lblTenSPTextValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTenSPTextValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabSPChiTiet;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGiaBanCu;
    private javax.swing.JLabel lblGiaBanMoi;
    private javax.swing.JLabel lblGiamGia;
    private java.awt.TextField lblTenSP;
    private javax.swing.JLabel lblThongTinHanSuDung;
    // End of variables declaration//GEN-END:variables
}
