/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Imac
 */
public class frmMainForm extends javax.swing.JFrame {

    /**
     * Creates new form frmMainForm
     */
    public frmMainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlViewPort = new javax.swing.JPanel();
        tabMain = new javax.swing.JTabbedPane();
        tabDangNhap = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnDangNhap1 = new javax.swing.JButton();
        btnHuy1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnQuenMK = new javax.swing.JButton();
        btnDangKy = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        panelTen1 = new javax.swing.JPanel();
        lblTenMatkhau = new javax.swing.JLabel();
        paneliputTen1 = new javax.swing.JPanel();
        inputLogin1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        panelTen2 = new javax.swing.JPanel();
        lblTen1 = new javax.swing.JLabel();
        paneliputTen2 = new javax.swing.JPanel();
        inputLogin2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        panelTen = new javax.swing.JPanel();
        lblTen = new javax.swing.JLabel();
        paneliputTen = new javax.swing.JPanel();
        rbtQuantrivien = new javax.swing.JRadioButton();
        rbtKhachhang = new javax.swing.JRadioButton();
        tabMuaHang = new javax.swing.JPanel();
        lblMuaHangTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMuaHang_TenSP = new javax.swing.JTextField();
        txtMuaHang_MaSP = new javax.swing.JTextField();
        txtMuaHang_GiaBan = new javax.swing.JTextField();
        txtMuaHang_SoLuong = new javax.swing.JTextField();
        sldSoLuong = new javax.swing.JSlider();
        cbbMuaHang_Loai = new javax.swing.JComboBox<>();
        btnMuaHang_TimKiem = new javax.swing.JButton();
        cbbMuaHang_TimKiem = new javax.swing.JComboBox<>();
        tabGioHang = new javax.swing.JPanel();
        tabQuanLy = new javax.swing.JTabbedPane();
        tabQuanLy_SanPham = new javax.swing.JPanel();
        tabQuanLy_HoaDon = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BachHoaXanh");
        setResizable(false);

        tabMain.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        btnDangNhap1.setText("Đăng Nhập");
        jPanel5.add(btnDangNhap1);

        btnHuy1.setText("Hủy");
        jPanel5.add(btnHuy1);

        btnQuenMK.setBackground(new java.awt.Color(51, 255, 255));
        btnQuenMK.setText("Quên Mật Khẩu");
        jPanel3.add(btnQuenMK);

        btnDangKy.setBackground(new java.awt.Color(51, 255, 255));
        btnDangKy.setText("Đăng Ký");
        jPanel3.add(btnDangKy);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.GridLayout());

        panelTen1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelTen1.setFocusable(false);
        panelTen1.setMinimumSize(new java.awt.Dimension(200, 50));
        panelTen1.setLayout(new javax.swing.BoxLayout(panelTen1, javax.swing.BoxLayout.LINE_AXIS));

        lblTenMatkhau.setText("Mật Khẩu:");
        lblTenMatkhau.setFocusable(false);
        lblTenMatkhau.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panelTen1.add(lblTenMatkhau);

        jPanel4.add(panelTen1);

        paneliputTen1.setLayout(new javax.swing.BoxLayout(paneliputTen1, javax.swing.BoxLayout.LINE_AXIS));
        paneliputTen1.add(inputLogin1);

        jPanel4.add(paneliputTen1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.GridLayout());

        panelTen2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelTen2.setFocusable(false);
        panelTen2.setMaximumSize(new java.awt.Dimension(50, 50));
        panelTen2.setMinimumSize(new java.awt.Dimension(50, 20));
        panelTen2.setLayout(new javax.swing.BoxLayout(panelTen2, javax.swing.BoxLayout.LINE_AXIS));

        lblTen1.setText("Tên Đăng Nhập:");
        lblTen1.setFocusable(false);
        lblTen1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panelTen2.add(lblTen1);

        jPanel2.add(panelTen2);

        paneliputTen2.setLayout(new javax.swing.BoxLayout(paneliputTen2, javax.swing.BoxLayout.LINE_AXIS));
        paneliputTen2.add(inputLogin2);

        jPanel2.add(paneliputTen2);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridLayout());

        panelTen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelTen.setFocusable(false);
        panelTen.setMaximumSize(new java.awt.Dimension(50, 50));
        panelTen.setMinimumSize(new java.awt.Dimension(50, 20));
        panelTen.setLayout(new javax.swing.BoxLayout(panelTen, javax.swing.BoxLayout.LINE_AXIS));

        lblTen.setText("Loại Tài Khoản:");
        lblTen.setFocusable(false);
        lblTen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panelTen.add(lblTen);

        jPanel1.add(panelTen);

        paneliputTen.setLayout(new javax.swing.BoxLayout(paneliputTen, javax.swing.BoxLayout.LINE_AXIS));

        rbtQuantrivien.setText("Quản Trị Viên");
        paneliputTen.add(rbtQuantrivien);

        rbtKhachhang.setText("Khách hàng");
        paneliputTen.add(rbtKhachhang);

        jPanel1.add(paneliputTen);

        javax.swing.GroupLayout tabDangNhapLayout = new javax.swing.GroupLayout(tabDangNhap);
        tabDangNhap.setLayout(tabDangNhapLayout);
        tabDangNhapLayout.setHorizontalGroup(
            tabDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1208, Short.MAX_VALUE)
            .addGroup(tabDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabDangNhapLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(tabDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        tabDangNhapLayout.setVerticalGroup(
            tabDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
            .addGroup(tabDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabDangNhapLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tabMain.addTab("Đăng Nhập", tabDangNhap);

        lblMuaHangTitle.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lblMuaHangTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMuaHangTitle.setText("Danh sách các sản phẩm");

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Loại", "Giá bán", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Mã sản phẩm");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Tên sản phẩm");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Loại");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Giá bán");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Số lượng");

        sldSoLuong.setMaximum(1000);
        sldSoLuong.setMinorTickSpacing(100);
        sldSoLuong.setPaintTicks(true);
        sldSoLuong.setSnapToTicks(true);

        cbbMuaHang_Loai.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cbbMuaHang_Loai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thịt, cá, trứng", "Rau, củ, quả, nấm", "Nước ngọt, sữa", " " }));

        btnMuaHang_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnMuaHang_TimKiem.setText("Tìm kiếm theo:");

        cbbMuaHang_TimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout tabMuaHangLayout = new javax.swing.GroupLayout(tabMuaHang);
        tabMuaHang.setLayout(tabMuaHangLayout);
        tabMuaHangLayout.setHorizontalGroup(
            tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabMuaHangLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tabMuaHangLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMuaHang_MaSP))
                    .addGroup(tabMuaHangLayout.createSequentialGroup()
                        .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbMuaHang_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMuaHang_TenSP)
                            .addComponent(txtMuaHang_GiaBan)
                            .addComponent(txtMuaHang_SoLuong)))
                    .addComponent(sldSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabMuaHangLayout.createSequentialGroup()
                        .addComponent(btnMuaHang_TimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbMuaHang_TimKiem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tabMuaHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMuaHangTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabMuaHangLayout.setVerticalGroup(
            tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMuaHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMuaHangTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addGroup(tabMuaHangLayout.createSequentialGroup()
                        .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtMuaHang_MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtMuaHang_TenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbMuaHang_Loai))
                        .addGap(18, 18, 18)
                        .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtMuaHang_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMuaHang_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(sldSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMuaHang_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbMuaHang_TimKiem))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabMain.addTab("Mua Hàng", tabMuaHang);

        javax.swing.GroupLayout tabGioHangLayout = new javax.swing.GroupLayout(tabGioHang);
        tabGioHang.setLayout(tabGioHangLayout);
        tabGioHangLayout.setHorizontalGroup(
            tabGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1208, Short.MAX_VALUE)
        );
        tabGioHangLayout.setVerticalGroup(
            tabGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        tabMain.addTab("Giỏ Hàng", tabGioHang);

        javax.swing.GroupLayout tabQuanLy_SanPhamLayout = new javax.swing.GroupLayout(tabQuanLy_SanPham);
        tabQuanLy_SanPham.setLayout(tabQuanLy_SanPhamLayout);
        tabQuanLy_SanPhamLayout.setHorizontalGroup(
            tabQuanLy_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1208, Short.MAX_VALUE)
        );
        tabQuanLy_SanPhamLayout.setVerticalGroup(
            tabQuanLy_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );

        tabQuanLy.addTab("Sản phẩm", tabQuanLy_SanPham);

        javax.swing.GroupLayout tabQuanLy_HoaDonLayout = new javax.swing.GroupLayout(tabQuanLy_HoaDon);
        tabQuanLy_HoaDon.setLayout(tabQuanLy_HoaDonLayout);
        tabQuanLy_HoaDonLayout.setHorizontalGroup(
            tabQuanLy_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1208, Short.MAX_VALUE)
        );
        tabQuanLy_HoaDonLayout.setVerticalGroup(
            tabQuanLy_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );

        tabQuanLy.addTab("Hóa Đơn", tabQuanLy_HoaDon);

        tabMain.addTab("Quản lý", tabQuanLy);

        javax.swing.GroupLayout pnlViewPortLayout = new javax.swing.GroupLayout(pnlViewPort);
        pnlViewPort.setLayout(pnlViewPortLayout);
        pnlViewPortLayout.setHorizontalGroup(
            pnlViewPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlViewPortLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabMain))
        );
        pnlViewPortLayout.setVerticalGroup(
            pnlViewPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMain)
        );

        tabMain.getAccessibleContext().setAccessibleName("tabMain");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlViewPort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlViewPort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnDangNhap1;
    private javax.swing.JButton btnHuy1;
    private javax.swing.JButton btnMuaHang_TimKiem;
    private javax.swing.JButton btnQuenMK;
    private javax.swing.JComboBox<String> cbbMuaHang_Loai;
    private javax.swing.JComboBox<String> cbbMuaHang_TimKiem;
    private javax.swing.JTextField inputLogin1;
    private javax.swing.JTextField inputLogin2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblMuaHangTitle;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTen1;
    private javax.swing.JLabel lblTenMatkhau;
    private javax.swing.JPanel panelTen;
    private javax.swing.JPanel panelTen1;
    private javax.swing.JPanel panelTen2;
    private javax.swing.JPanel paneliputTen;
    private javax.swing.JPanel paneliputTen1;
    private javax.swing.JPanel paneliputTen2;
    private javax.swing.JPanel pnlViewPort;
    private javax.swing.JRadioButton rbtKhachhang;
    private javax.swing.JRadioButton rbtQuantrivien;
    private javax.swing.JSlider sldSoLuong;
    private javax.swing.JPanel tabDangNhap;
    private javax.swing.JPanel tabGioHang;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JPanel tabMuaHang;
    private javax.swing.JTabbedPane tabQuanLy;
    private javax.swing.JPanel tabQuanLy_HoaDon;
    private javax.swing.JPanel tabQuanLy_SanPham;
    private javax.swing.JTextField txtMuaHang_GiaBan;
    private javax.swing.JTextField txtMuaHang_MaSP;
    private javax.swing.JTextField txtMuaHang_SoLuong;
    private javax.swing.JTextField txtMuaHang_TenSP;
    // End of variables declaration//GEN-END:variables
}
