/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.DSSanPham;
import model.SanPham;
import sokkimthanh.frmAdminSanPham;
//import sun.swing.table.DefaultTableCellHeaderRenderer;

/**
 *
 * @author Imac
 */
public class frmMainForm extends javax.swing.JFrame {

    /**
     * Creates new form frmMainForm
     */
    private DSSanPham listSP = new DSSanPham();
    private int timKiem;

    public frmMainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlViewPort = new javax.swing.JPanel();
        tabMain = new javax.swing.JTabbedPane();
        tabDangNhap = new javax.swing.JPanel();
        tabMuaHang = new javax.swing.JPanel();
        lblMuaHangTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMuaHang_DanhSach = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMuaHang_TenSP = new javax.swing.JTextField();
        txtMuaHang_MaSP = new javax.swing.JTextField();
        txtMuaHang_GiaBan = new javax.swing.JTextField();
        txtMuaHang_SoLuong = new javax.swing.JTextField();
        sldMuaHang_SoLuong = new javax.swing.JSlider();
        cbbMuaHang_Loai = new javax.swing.JComboBox<>();
        btnMuaHang_TimKiem = new javax.swing.JButton();
        cbbMuaHang_TimKiem = new javax.swing.JComboBox<>();
        lblMuaHang_MinSoLuong = new javax.swing.JLabel();
        lblMuaHang_MaxSoLuong = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tabGioHang = new javax.swing.JPanel();
        tabQuanLy = new javax.swing.JTabbedPane();
        tabQuanLy_SanPham = new javax.swing.JPanel();
        tabQuanLy_HoaDon = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BachHoaXanh");
        setResizable(false);

        tabMain.setBackground(new java.awt.Color(255, 255, 255));
        tabMain.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabMain.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabMainStateChanged(evt);
            }
        });

        javax.swing.GroupLayout tabDangNhapLayout = new javax.swing.GroupLayout(tabDangNhap);
        tabDangNhap.setLayout(tabDangNhapLayout);
        tabDangNhapLayout.setHorizontalGroup(
            tabDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 923, Short.MAX_VALUE)
        );
        tabDangNhapLayout.setVerticalGroup(
            tabDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        tabMain.addTab("Đăng Nhập", tabDangNhap);

        tabMuaHang.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        lblMuaHangTitle.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lblMuaHangTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMuaHangTitle.setText("Danh sách các sản phẩm");

        tblMuaHang_DanhSach.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tblMuaHang_DanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên sản phẩm", "Loại", "Giá", "SL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMuaHang_DanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMuaHang_DanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMuaHang_DanhSach);
        if (tblMuaHang_DanhSach.getColumnModel().getColumnCount() > 0) {
            tblMuaHang_DanhSach.getColumnModel().getColumn(0).setResizable(false);
            tblMuaHang_DanhSach.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblMuaHang_DanhSach.getColumnModel().getColumn(1).setResizable(false);
            tblMuaHang_DanhSach.getColumnModel().getColumn(1).setPreferredWidth(160);
            tblMuaHang_DanhSach.getColumnModel().getColumn(2).setResizable(false);
            tblMuaHang_DanhSach.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblMuaHang_DanhSach.getColumnModel().getColumn(3).setResizable(false);
            tblMuaHang_DanhSach.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Mã sản phẩm");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Tên sản phẩm");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Loại");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Giá bán");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Số lượng");

        txtMuaHang_TenSP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtMuaHang_TenSP.setEnabled(false);

        txtMuaHang_MaSP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtMuaHang_MaSP.setEnabled(false);

        txtMuaHang_GiaBan.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtMuaHang_GiaBan.setEnabled(false);
        txtMuaHang_GiaBan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMuaHang_GiaBanKeyPressed(evt);
            }
        });

        txtMuaHang_SoLuong.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtMuaHang_SoLuong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMuaHang_SoLuong.setEnabled(false);
        txtMuaHang_SoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMuaHang_SoLuongKeyPressed(evt);
            }
        });

        sldMuaHang_SoLuong.setMajorTickSpacing(200);
        sldMuaHang_SoLuong.setMaximum(1000);
        sldMuaHang_SoLuong.setMinorTickSpacing(50);
        sldMuaHang_SoLuong.setPaintTicks(true);
        sldMuaHang_SoLuong.setEnabled(false);
        sldMuaHang_SoLuong.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldMuaHang_SoLuongStateChanged(evt);
            }
        });

        cbbMuaHang_Loai.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cbbMuaHang_Loai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thịt, cá, trứng", "Rau, củ, quả, nấm", "Nước ngọt, sữa", " " }));
        cbbMuaHang_Loai.setEnabled(false);

        btnMuaHang_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnMuaHang_TimKiem.setText("Tìm kiếm theo:");
        btnMuaHang_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuaHang_TimKiemActionPerformed(evt);
            }
        });

        cbbMuaHang_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cbbMuaHang_TimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã", "Tên", "Loại", "Giá bán", "Số lượng" }));
        cbbMuaHang_TimKiem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbMuaHang_TimKiemItemStateChanged(evt);
            }
        });

        lblMuaHang_MinSoLuong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMuaHang_MinSoLuong.setText("0");

        lblMuaHang_MaxSoLuong.setText("1000");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_Plus_Item-removebg-preview.png"))); // NOI18N
        jButton1.setText("Thêm vào giỏ hàng");

        javax.swing.GroupLayout tabMuaHangLayout = new javax.swing.GroupLayout(tabMuaHang);
        tabMuaHang.setLayout(tabMuaHangLayout);
        tabMuaHangLayout.setHorizontalGroup(
            tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabMuaHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMuaHangTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabMuaHangLayout.createSequentialGroup()
                        .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabMuaHangLayout.createSequentialGroup()
                                .addComponent(lblMuaHang_MinSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMuaHang_MaxSoLuong))
                            .addComponent(sldMuaHang_SoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(tabMuaHangLayout.createSequentialGroup()
                                .addComponent(btnMuaHang_TimKiem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbMuaHang_TimKiem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(tabMuaHangLayout.createSequentialGroup()
                                .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(tabMuaHangLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMuaHang_MaSP))
                                    .addGroup(tabMuaHangLayout.createSequentialGroup()
                                        .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbbMuaHang_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMuaHang_TenSP)
                                            .addComponent(txtMuaHang_GiaBan)
                                            .addComponent(txtMuaHang_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabMuaHangLayout.setVerticalGroup(
            tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMuaHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMuaHangTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addGroup(tabMuaHangLayout.createSequentialGroup()
                        .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMuaHang_MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMuaHang_TenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbMuaHang_Loai))
                        .addGap(18, 18, 18)
                        .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMuaHang_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMuaHang_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sldMuaHang_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMuaHang_MinSoLuong)
                            .addComponent(lblMuaHang_MaxSoLuong))
                        .addGap(18, 18, 18)
                        .addGroup(tabMuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMuaHang_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbMuaHang_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );

        tabMain.addTab("Mua Hàng", new javax.swing.ImageIcon(getClass().getResource("/images/icon_MuaHang-removebg-preview.png")), tabMuaHang); // NOI18N

        javax.swing.GroupLayout tabGioHangLayout = new javax.swing.GroupLayout(tabGioHang);
        tabGioHang.setLayout(tabGioHangLayout);
        tabGioHangLayout.setHorizontalGroup(
            tabGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 923, Short.MAX_VALUE)
        );
        tabGioHangLayout.setVerticalGroup(
            tabGioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        tabMain.addTab("Giỏ Hàng", tabGioHang);

        tabQuanLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabQuanLyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tabQuanLy_SanPhamLayout = new javax.swing.GroupLayout(tabQuanLy_SanPham);
        tabQuanLy_SanPham.setLayout(tabQuanLy_SanPhamLayout);
        tabQuanLy_SanPhamLayout.setHorizontalGroup(
            tabQuanLy_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
        );
        tabQuanLy_SanPhamLayout.setVerticalGroup(
            tabQuanLy_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
        );

        tabQuanLy.addTab("Sản phẩm", tabQuanLy_SanPham);

        javax.swing.GroupLayout tabQuanLy_HoaDonLayout = new javax.swing.GroupLayout(tabQuanLy_HoaDon);
        tabQuanLy_HoaDon.setLayout(tabQuanLy_HoaDonLayout);
        tabQuanLy_HoaDonLayout.setHorizontalGroup(
            tabQuanLy_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
        );
        tabQuanLy_HoaDonLayout.setVerticalGroup(
            tabQuanLy_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
        );

        tabQuanLy.addTab("Hóa Đơn", tabQuanLy_HoaDon);

        tabMain.addTab("Quản lý", tabQuanLy);

        javax.swing.GroupLayout pnlViewPortLayout = new javax.swing.GroupLayout(pnlViewPort);
        pnlViewPort.setLayout(pnlViewPortLayout);
        pnlViewPortLayout.setHorizontalGroup(
            pnlViewPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlViewPortLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabMain))
        );
        pnlViewPortLayout.setVerticalGroup(
            pnlViewPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMain, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );

        tabMain.getAccessibleContext().setAccessibleName("tabMain");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlViewPort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlViewPort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabMainStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabMainStateChanged
        // TODO add your handling code here:
        if (tabMuaHang.isShowing()) {
            cbbMuaHang_TimKiem.setSelectedIndex(0);
            this.timKiem = 0;
            Hide();
            txtMuaHang_MaSP.setEnabled(true);
            listSP.DocDL();

//            DefaultTableCellRenderer centerCell = new DefaultTableCellHeaderRenderer();
            DefaultTableCellRenderer centerCell = new DefaultTableCellRenderer();
            centerCell.setHorizontalAlignment(JLabel.CENTER);
            for (int i = 0; i < tblMuaHang_DanhSach.getColumnCount(); i++) {
                tblMuaHang_DanhSach.getColumnModel().getColumn(i).setCellRenderer(centerCell);
            }
            ShowTable();
        }
    }//GEN-LAST:event_tabMainStateChanged

    private void cbbMuaHang_TimKiemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbMuaHang_TimKiemItemStateChanged
        // TODO add your handling code here:
        timKiem = cbbMuaHang_TimKiem.getSelectedIndex();
        Hide();
        switch (timKiem) {
            case 0:
                txtMuaHang_MaSP.setEnabled(true);
                txtMuaHang_MaSP.requestFocus();
                break;
            case 1:
                txtMuaHang_TenSP.setEnabled(true);
                txtMuaHang_TenSP.requestFocus();
                break;
            case 2:
                cbbMuaHang_Loai.setEnabled(true);
                break;
            case 3:
                txtMuaHang_GiaBan.setEnabled(true);
                txtMuaHang_GiaBan.requestFocus();
                break;
            default:
                txtMuaHang_SoLuong.setEnabled(true);
                txtMuaHang_SoLuong.requestFocus();
                sldMuaHang_SoLuong.setEnabled(true);
                break;
        }
        System.out.println(timKiem);
    }//GEN-LAST:event_cbbMuaHang_TimKiemItemStateChanged

    private void sldMuaHang_SoLuongStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldMuaHang_SoLuongStateChanged
        // TODO add your handling code here:
        txtMuaHang_SoLuong.setText(sldMuaHang_SoLuong.getValue() + "");
    }//GEN-LAST:event_sldMuaHang_SoLuongStateChanged

    private void txtMuaHang_SoLuongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMuaHang_SoLuongKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                int soLuong = Integer.parseInt(txtMuaHang_SoLuong.getText());
                if (soLuong >= 0 && soLuong <= 1000) {
                    sldMuaHang_SoLuong.setValue(soLuong);
                } else {
                    throw new NumberFormatException();
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Số lượng sản phẩm phải là số nguyên từ 0 - 1000");
                txtMuaHang_SoLuong.setText("0");
                sldMuaHang_SoLuong.setValue(0);
            }
        }
    }//GEN-LAST:event_txtMuaHang_SoLuongKeyPressed

    private void txtMuaHang_GiaBanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMuaHang_GiaBanKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if ((key < KeyEvent.VK_0 || key > KeyEvent.VK_9) && key != KeyEvent.VK_BACK_SPACE && key != KeyEvent.VK_ENTER) {
            JOptionPane.showMessageDialog(rootPane, "Giá bán chỉ được phép điền số nguyên dương");
            txtMuaHang_GiaBan.setText(txtMuaHang_GiaBan.getText().substring(0, txtMuaHang_GiaBan.getText().length() - 1));
        }
    }//GEN-LAST:event_txtMuaHang_GiaBanKeyPressed

    private void btnMuaHang_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuaHang_TimKiemActionPerformed
        // TODO add your handling code here:
        switch (timKiem) {
            case 0:
                listSP.TimKiem_MaSP(txtMuaHang_MaSP.getText());
                break;
            case 1:
                listSP.TimKiem_TenSP(txtMuaHang_TenSP.getText());
                break;
            case 2:
                listSP.TimKiem_LoaiSP(cbbMuaHang_Loai.getSelectedIndex());
                break;
            case 3:
                listSP.TimKiem_GiaSP(Double.parseDouble(txtMuaHang_GiaBan.getText()));
                break;
            default:
                listSP.TimKiem_TonKho(sldMuaHang_SoLuong.getValue());
                break;
        }
        Hide();
        timKiem = 0;
        txtMuaHang_MaSP.setEnabled(true);
        cbbMuaHang_Loai.setSelectedIndex(0);
        cbbMuaHang_TimKiem.setSelectedIndex(0);
        ShowTable();
    }//GEN-LAST:event_btnMuaHang_TimKiemActionPerformed

    private void tblMuaHang_DanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMuaHang_DanhSachMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) tblMuaHang_DanhSach.getModel();
        txtMuaHang_MaSP.setText(tblModel.getValueAt(tblMuaHang_DanhSach.getSelectedRow(), 0).toString());
        txtMuaHang_TenSP.setText(tblModel.getValueAt(tblMuaHang_DanhSach.getSelectedRow(), 1).toString());
        String loai = tblModel.getValueAt(tblMuaHang_DanhSach.getSelectedRow(), 2).toString();
        if (loai.contains("Thit")) {
            cbbMuaHang_Loai.setSelectedIndex(0);
        } else if (loai.contains("Rau")) {
            cbbMuaHang_Loai.setSelectedIndex(1);
        } else {
            cbbMuaHang_Loai.setSelectedIndex(2);
        }
        txtMuaHang_GiaBan.setText(tblModel.getValueAt(tblMuaHang_DanhSach.getSelectedRow(), 3).toString());
        txtMuaHang_SoLuong.setText(tblModel.getValueAt(tblMuaHang_DanhSach.getSelectedRow(), 4).toString());
        sldMuaHang_SoLuong.setValue(Integer.parseInt(txtMuaHang_SoLuong.getText()));
    }//GEN-LAST:event_tblMuaHang_DanhSachMouseClicked

    private void tabQuanLyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabQuanLyMouseClicked
        frmAdminSanPham s = new frmAdminSanPham();
        s.setVisible(true);
    }//GEN-LAST:event_tabQuanLyMouseClicked

    private void Hide() {
        //Set null texts
        txtMuaHang_MaSP.setText(null);
        txtMuaHang_TenSP.setText(null);
        txtMuaHang_GiaBan.setText(null);
        txtMuaHang_SoLuong.setText(null);
        cbbMuaHang_Loai.setSelectedIndex(0);
        sldMuaHang_SoLuong.setValue(0);

        //Deactivate enable
        txtMuaHang_MaSP.setEnabled(false);
        txtMuaHang_TenSP.setEnabled(false);
        txtMuaHang_GiaBan.setEnabled(false);
        txtMuaHang_SoLuong.setEnabled(false);
        cbbMuaHang_Loai.setEnabled(false);
        sldMuaHang_SoLuong.setEnabled(false);
    }

    private void ShowTable() {
        DefaultTableModel model = (DefaultTableModel) tblMuaHang_DanhSach.getModel();
        model.setRowCount(0);

        //doi int loaisanpham sang string loaisanpham
        for (SanPham sanPham : listSP.getData()) {
            String loai = "";
            switch (sanPham.getLoaiSP()) {
                case 0:
                    loai = "Thit, ca, trung";
                    break;
                case 1:
                    loai = "Rau, cu, qua, nam";
                    break;
                default:
                    loai = "Nuoc, sua";
                    break;
            }
            Object[] rowData = new Object[]{sanPham.getMaSP(), sanPham.getTenSP(), loai, sanPham.getGiaSP(), sanPham.getTonKho()};
            model.addRow(rowData);
        }
        listSP.XuatDS();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMuaHang_TimKiem;
    private javax.swing.JComboBox<String> cbbMuaHang_Loai;
    private javax.swing.JComboBox<String> cbbMuaHang_TimKiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMuaHangTitle;
    private javax.swing.JLabel lblMuaHang_MaxSoLuong;
    private javax.swing.JLabel lblMuaHang_MinSoLuong;
    private javax.swing.JPanel pnlViewPort;
    private javax.swing.JSlider sldMuaHang_SoLuong;
    private javax.swing.JPanel tabDangNhap;
    private javax.swing.JPanel tabGioHang;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JPanel tabMuaHang;
    private javax.swing.JTabbedPane tabQuanLy;
    private javax.swing.JPanel tabQuanLy_HoaDon;
    private javax.swing.JPanel tabQuanLy_SanPham;
    private javax.swing.JTable tblMuaHang_DanhSach;
    private javax.swing.JTextField txtMuaHang_GiaBan;
    private javax.swing.JTextField txtMuaHang_MaSP;
    private javax.swing.JTextField txtMuaHang_SoLuong;
    private javax.swing.JTextField txtMuaHang_TenSP;
    // End of variables declaration//GEN-END:variables
}
