/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sokkimthanh.admin.sanpham;

/**
 *
 * @author Thanh
 */
public class frmAdminSanPham extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public frmAdminSanPham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        divTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        divInfo = new javax.swing.JPanel();
        divInput = new javax.swing.JPanel();
        divTenSP = new javax.swing.JPanel();
        lblTenSP = new javax.swing.JLabel();
        inputTenSP = new javax.swing.JTextField();
        divGiaTien = new javax.swing.JPanel();
        lblGiaTien = new javax.swing.JLabel();
        inputGiaTien = new javax.swing.JTextField();
        divButton = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        divSearch = new javax.swing.JPanel();
        panelSearch = new javax.swing.JPanel();
        inputSearch1 = new javax.swing.JTextField();
        ckbSearch1 = new javax.swing.JCheckBox();
        btnSearch1 = new javax.swing.JButton();
        divTable = new javax.swing.JPanel();
        scrollSanPham = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 173));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setLabelFor(this);
        lblTitle.setText("Danh mục sản phẩm");
        lblTitle.setToolTipText("Danh mục sản phẩm");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        divTitle.add(lblTitle);

        getContentPane().add(divTitle);

        divInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        divInfo.setLayout(new javax.swing.BoxLayout(divInfo, javax.swing.BoxLayout.PAGE_AXIS));

        divInput.setLayout(new java.awt.GridLayout(2, 0, 8, 8));

        divTenSP.setLayout(new java.awt.GridLayout(1, 0, 8, 8));

        lblTenSP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTenSP.setText("Tên sản phẩm");
        lblTenSP.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lblTenSP.setMaximumSize(new java.awt.Dimension(20, 18));
        divTenSP.add(lblTenSP);

        inputTenSP.setColumns(1);
        inputTenSP.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputTenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTenSPActionPerformed(evt);
            }
        });
        divTenSP.add(inputTenSP);

        divInput.add(divTenSP);

        divGiaTien.setLayout(new java.awt.GridLayout(1, 0, 8, 8));

        lblGiaTien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGiaTien.setText("Giá tiền");
        lblGiaTien.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lblGiaTien.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        divGiaTien.add(lblGiaTien);

        inputGiaTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGiaTienActionPerformed(evt);
            }
        });
        divGiaTien.add(inputGiaTien);

        divInput.add(divGiaTien);

        divInfo.add(divInput);

        divButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        divButton.add(btnThem);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        divButton.add(btnXoa);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        divButton.add(btnSua);

        divInfo.add(divButton);

        getContentPane().add(divInfo);

        divSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        divSearch.setLayout(new javax.swing.BoxLayout(divSearch, javax.swing.BoxLayout.PAGE_AXIS));

        panelSearch.setLayout(new javax.swing.BoxLayout(panelSearch, javax.swing.BoxLayout.LINE_AXIS));
        panelSearch.add(inputSearch1);

        ckbSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbSearch1ActionPerformed(evt);
            }
        });
        panelSearch.add(ckbSearch1);

        btnSearch1.setText("Tìm");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        panelSearch.add(btnSearch1);

        divSearch.add(panelSearch);

        divTable.setLayout(new javax.swing.BoxLayout(divTable, javax.swing.BoxLayout.LINE_AXIS));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollSanPham.setViewportView(tblSanPham);

        divTable.add(scrollSanPham);

        divSearch.add(divTable);

        getContentPane().add(divSearch);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void ckbSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbSearch1ActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

    }//GEN-LAST:event_btnThemActionPerformed

    private void inputGiaTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGiaTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGiaTienActionPerformed

    private void inputTenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTenSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTenSPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdminSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdminSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdminSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdminSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdminSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JCheckBox ckbSearch1;
    private javax.swing.JPanel divButton;
    private javax.swing.JPanel divGiaTien;
    private javax.swing.JPanel divInfo;
    private javax.swing.JPanel divInput;
    private javax.swing.JPanel divSearch;
    private javax.swing.JPanel divTable;
    private javax.swing.JPanel divTenSP;
    private javax.swing.JPanel divTitle;
    private javax.swing.JTextField inputGiaTien;
    private javax.swing.JTextField inputSearch1;
    private javax.swing.JTextField inputTenSP;
    private javax.swing.JLabel lblGiaTien;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JScrollPane scrollSanPham;
    private javax.swing.JTable tblSanPham;
    // End of variables declaration//GEN-END:variables
}
