/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sokkimthanh.admin.sanpham;

/**
 *
 * @author Thanh
 */
public class panelEditSanpham extends javax.swing.JPanel {

    /**
     * Creates new form panelAddEditSanpham
     */
    public panelEditSanpham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel7 = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblTenSanPham = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtTenSanPham = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        lblGiaTien = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        txtGiaTien = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        lblLoaiSanPham = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        cboLoaiSanPham = new javax.swing.JComboBox<>();
        jPanel15 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnHuy = new javax.swing.JButton();

        setBackground(java.awt.Color.white);
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(300, 350));
        setLayout(new java.awt.GridBagLayout());

        jPanel7.setBackground(java.awt.Color.white);
        jPanel7.setForeground(java.awt.Color.black);
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        lblTieuDe.setBackground(java.awt.Color.white);
        lblTieuDe.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblTieuDe.setForeground(java.awt.Color.black);
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("Cập nhật thông tin sản phẩm");
        lblTieuDe.setToolTipText("");
        lblTieuDe.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblTieuDe.setFocusable(false);
        lblTieuDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setName(""); // NOI18N
        jPanel7.add(lblTieuDe);
        lblTieuDe.getAccessibleContext().setAccessibleDescription("Thêm mới sản phẩm");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(jPanel7, gridBagConstraints);

        jPanel14.setBackground(java.awt.Color.white);
        jPanel14.setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setForeground(java.awt.Color.black);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        lblTenSanPham.setForeground(java.awt.Color.black);
        lblTenSanPham.setText("Tên Sản phẩm");
        jPanel3.add(lblTenSanPham, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel3);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        txtTenSanPham.setBackground(java.awt.Color.white);
        txtTenSanPham.setForeground(java.awt.Color.black);
        txtTenSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSanPhamActionPerformed(evt);
            }
        });
        jPanel2.add(txtTenSanPham);

        jPanel1.add(jPanel2);

        jPanel14.add(jPanel1);

        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        jPanel17.setBackground(java.awt.Color.white);
        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel17.setForeground(java.awt.Color.black);
        jPanel17.setLayout(new java.awt.GridBagLayout());

        lblGiaTien.setBackground(java.awt.Color.white);
        lblGiaTien.setForeground(java.awt.Color.black);
        lblGiaTien.setText("Giá Tiền");
        jPanel17.add(lblGiaTien, new java.awt.GridBagConstraints());

        jPanel16.add(jPanel17);

        jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.LINE_AXIS));

        txtGiaTien.setBackground(java.awt.Color.white);
        txtGiaTien.setForeground(java.awt.Color.black);
        txtGiaTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTienActionPerformed(evt);
            }
        });
        jPanel18.add(txtGiaTien);

        jPanel16.add(jPanel18);

        jPanel14.add(jPanel16);

        jPanel19.setLayout(new java.awt.GridLayout(1, 0));

        jPanel20.setBackground(java.awt.Color.white);
        jPanel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel20.setForeground(java.awt.Color.black);
        jPanel20.setLayout(new java.awt.GridBagLayout());

        lblLoaiSanPham.setBackground(java.awt.Color.white);
        lblLoaiSanPham.setForeground(java.awt.Color.black);
        lblLoaiSanPham.setText("Loại sản phẩm");
        jPanel20.add(lblLoaiSanPham, new java.awt.GridBagConstraints());

        jPanel19.add(jPanel20);

        jPanel21.setLayout(new javax.swing.BoxLayout(jPanel21, javax.swing.BoxLayout.LINE_AXIS));

        cboLoaiSanPham.setBackground(java.awt.Color.white);
        cboLoaiSanPham.setForeground(java.awt.Color.black);
        cboLoaiSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trứng sữa", "thịt", "rau củ quả" }));
        jPanel21.add(cboLoaiSanPham);

        jPanel19.add(jPanel21);

        jPanel14.add(jPanel19);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(jPanel14, gridBagConstraints);

        jPanel15.setBackground(java.awt.Color.white);
        jPanel15.setAutoscrolls(true);
        jPanel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.setFocusCycleRoot(true);
        jPanel15.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel15.setPreferredSize(new java.awt.Dimension(100, 20));
        java.awt.GridBagLayout jPanel15Layout1 = new java.awt.GridBagLayout();
        jPanel15Layout1.columnWidths = new int[] {0, 5, 0, 5, 0};
        jPanel15Layout1.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel15.setLayout(jPanel15Layout1);

        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        btnThem.setBackground(new java.awt.Color(56, 114, 176));
        btnThem.setForeground(java.awt.Color.white);
        btnThem.setText("Cập nhật");
        btnThem.setMaximumSize(new java.awt.Dimension(100, 100));
        btnThem.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel5.add(btnThem);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        jPanel15.add(jPanel5, gridBagConstraints);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        btnHuy.setForeground(java.awt.Color.white);
        btnHuy.setText("Quay lại");
        jPanel6.add(btnHuy);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        jPanel15.add(jPanel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel15, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSanPhamActionPerformed

    private void txtGiaTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTienActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cboLoaiSanPham;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblGiaTien;
    private javax.swing.JLabel lblLoaiSanPham;
    private javax.swing.JLabel lblTenSanPham;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtTenSanPham;
    // End of variables declaration//GEN-END:variables
}
